# Generated by Django 4.2.4 on 2023-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_todo_date_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('STUDY', 'STUDY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
